# Generated by Django 2.0.5 on 2018-05-25 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Door',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(max_length=200)),
                ('level', models.CharField(choices=[('1', '低'), ('2', '中'), ('3', '高')], default='3', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='DoorOpen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='time')),
                ('door', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.Door')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('privilege', models.CharField(choices=[('1', '低'), ('2', '中'), ('3', '高')], default='1', max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='dooropen',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.Person'),
        ),
    ]
