# Generated by Django 2.0.5 on 2018-05-25 09:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_auto_20180525_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='door',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
